name: Bug Report
description: Report a bug you've found
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the form below to help us understand and fix the issue.

  - type: input
    id: title
    attributes:
      label: Title
      description: Brief description of the bug
      placeholder: e.g., "Login fails with special characters in password"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description of the bug
      placeholder: |
        Describe what happened and what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the bug
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        - OS: (e.g., macOS, Windows, Linux)
        - Node version: (run `node --version`)
        - Browser: (if frontend issue)
        - Browser version:
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add any relevant screenshots

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Paste any relevant error logs or stack traces
      render: bash
