name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for the feature request! Help us understand your idea.

  - type: input
    id: title
    attributes:
      label: Title
      description: Brief description of the feature
      placeholder: e.g., "Add email notifications for appointments"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem or use case
      placeholder: |
        As a [user role], I need [feature] so that [benefit].
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Any other approaches you've considered?

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information?
